### **NORMALIZATION PROBLEM** 
---

In [24]:
import numpy as np              #For Numpy we must called the Numpy library
X = np.random.random((5, 5))    #Create a random 5x5 ndarray
print (X)                       #This will serve as the original X

[[0.67817891 0.31366154 0.57525651 0.32282168 0.61647751]
 [0.11830064 0.79067885 0.12921478 0.8038815  0.12959708]
 [0.82880854 0.72024453 0.69075244 0.54014456 0.05485816]
 [0.67512722 0.83486212 0.51502975 0.56962667 0.81783996]
 [0.20374884 0.10838722 0.60813684 0.28702085 0.87157116]]


In [25]:
mean = X.mean()                              #This is to compute the mean and standard deviation of X using the .mean() and .std() calls
std = X.std()
X_normalized = (X - mean) / std              #To noramlize X we serve it as the given formula

np.save("X_normalized.npy", X_normalized)    #Save the noramlize X as "X_normalize.npy"

print("Original X:\n", X)
print("\nNormalized X:\n", X_normalized)

Original X:
 [[0.67817891 0.31366154 0.57525651 0.32282168 0.61647751]
 [0.11830064 0.79067885 0.12921478 0.8038815  0.12959708]
 [0.82880854 0.72024453 0.69075244 0.54014456 0.05485816]
 [0.67512722 0.83486212 0.51502975 0.56962667 0.81783996]
 [0.20374884 0.10838722 0.60813684 0.28702085 0.87157116]]

Normalized X:
 [[ 0.62066485 -0.74216509  0.23586639 -0.70791786  0.38998034]
 [-1.47256563  1.04127111 -1.4317607   1.09063219 -1.43033138]
 [ 1.18382751  0.77793662  0.66767383  0.10459247 -1.7097596 ]
 [ 0.60925544  1.2064602   0.01069512  0.21481795  1.14281901]
 [-1.15309837 -1.50962917  0.35879689 -0.84176728  1.34370516]]


### **DIVISIBLE BY 3 PROBLEM**
---

In [29]:
import numpy as np           #Called the Numpy Library
A = np.arange(1, 101)**2     #Created array of squares of first 100 positive integers

A = A.reshape(10, 10)        #Reshaped into 10x10 ndarray
print(A)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [30]:
div_by_3 = A[A % 3 == 0]                          #Determine all the numbers divisible by 3

np.save("div_by_3.npy", div_by_3)                 #Save the result as "div_by_3.npy"

print("Elements divisible by 3:\n", div_by_3)

Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
